contact_links:
  - name: Join nf-core
    url: https://nf-co.re/join
    about: Please join the nf-core community here
  - name: "Slack #atacseq channel"
    url: https://nfcore.slack.com/channels/atacseq
    about: Discussion about the nf-core/atacseq pipeline
